# Generated by Django 5.0 on 2023-12-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dixscount_percentage',
            field=models.IntegerField(default=10),
        ),
    ]
